import Head from 'next/head'
import Image from 'next/image'
import { Inter } from '@next/font/google'
import styles from '../styles/Home.module.css'
import { useState } from 'react'

const inter = Inter({ subsets: ['latin'] })

export default function Home() {
  const [count,setCount] = useState(0)
  const handle = (val)=>{
    setCount(count + val)
  }
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className={styles.main}>
        <h1>Counter - App</h1>
        <h2>Count:{count}</h2>
        <div className={styles.btn}>
        <button disabled={count==0} onClick={()=>handle(-1)}>DEC</button>
        <button disabled={count==5} onClick={()=>handle(1)}>INC</button>
        </div>

      </main>
    </>
  )
}
